# Generated by Django 5.2.15 on 2026-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('description_fa', models.TextField(blank=True, verbose_name='Description (FA)')),
                ('url', models.URLField(blank=True, verbose_name='Live URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('tags', models.JSONField(default=list, help_text='e.g. ["Next.js", "Django"]')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('in_progress', 'In Progress')], default='active', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for work')),
                ('status_text', models.CharField(default='Available for work', max_length=100)),
                ('status_text_fa', models.CharField(default='آماده همکاری', max_length=100, verbose_name='Status text (FA)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Status',
                'verbose_name_plural': 'Site Status',
            },
        ),
    ]
