# Generated by Django 5.2.15 on 2026-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name (FA)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(default=list, help_text='e.g. ["Next.js", "Django"]', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='sitestatus',
            name='status_text',
            field=models.CharField(default='Available for work', max_length=100, verbose_name='Status text'),
        ),
        migrations.AlterField(
            model_name='sitestatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
